version: "3.3"
services:
  ascent-amqp:
    build:
      context: .
    depends_on:
      - consul
      - vault
    logging:
      driver: json-file

  ###### Vault ##########

  vault:
    image: ascent/ascent-vault
    hostname: vault
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_DEV_ROOT_TOKEN_ID=vaultroot
      - tls_disable=1
      - GIT_ACCESS_TOKEN=$GIT_ACCESS_TOKEN
    ports:
      - 8200
    command: server -dev
    networks:
      - ascentnet

networks:
  ascentnet:
    driver: ${DRIVER_TYPE:-bridge}
